### ISSUE TITLE
add an NPC

### ISSUE THREAD

**Issue by JeroUwU** [pege22/pege_source_main#14]
try the npc's interaction

**Comment by LUIS9799** [comment]
Npc's interaction will includes later, actually npc's interactions are in pre-desing in order to include a solid that displays dialogs wihout changing scenes o post requests, it means that dialogflow will be appear in game without changing canvas visibility, @JeroUwU will help to implement some solids from npc"s and then and interaction with OnCollide() condition

**Comment by LUIS9799** [comment]
Added without interactions, working on it..

**Comment by LUIS9799** [comment]
Added ;)
